### ISSUE TITLE
graph frames

### ISSUE THREAD

**Issue by geoHeil** [sparkling-graph/sparkling-graph#11]
Are there any plans to move from graphX to graphFrames?

**Comment by blacknred0** [comment]
I think that will be a whole new project by itself, since graphframes calls to the API are different than GraphX.

On Jan 28, 2017, at 3:16 AM, geoHeil <notifications@github.com> wrote:

Are there any plans to move from graphX to graphFrames?

**Comment by riomus** [comment]
I need to look at GraphFrames API. For sure currently, it is not possible to switch fully to GraphFrames, because spark is officially using GraphX as graph solution. We can try to support both solutions using appropriate adapters. For seamless usage, some scala implicit tricks can be used.

**Comment by riomus** [comment]
Ok so I've read some info about GraphFrames. In my opinion, we should migrate code to graph frames. Because of plenty tests, it should not be so painful. Only thing is that after migration, we should change major version.

**Comment by blacknred0** [comment]
are you thinking that GraphFrames will be the version supported going forward?  Meaning making the switch instead of maintaining two codes (one for RDDs and the other for GraphFrames)?

**Comment by riomus** [comment]
According to my knowledge (from articles and other info about Spark) RDD graph API is only kept because of backward compatibility. GrpahFrames are based on DataFrames that are faster than RDD (which are quite old now). There is also an option to create implicit conversions from GraphgFrame and Graph into SparklingGraph data structure that will wrap API from both approaches.

**Comment by riomus** [comment]
Hi

I am starting development on  separate branch for now [graphFrames](https://github.com/sparkling-graph/sparkling-graph/tree/graphFrames)

**Comment by riomus** [comment]
After multiple tries and approaches to implementation support for GraphFrames, I must postpone it for now and close that issue. Currently, I do not see a possibility to do that because of lack of multiple functionalities in graph frames. There is no point to do that if internally we will be switching from GraphFrames to RDD API.
