### ISSUE TITLE
[question] Modify EigenvectorCentrality

### ISSUE THREAD

**Issue by geoHeil** [sparkling-graph/sparkling-graph#12]
I have a question about modifying eigenvector centrality.

As @riomus pointed out here https://github.com/sparkling-graph/sparkling-graph/issues/10 I should have a look at EigenvectorCentrality and GraphX to properly implement the iterative pregel approach. After having a look at it and modifying the class here https://github.com/geoHeil/graphFrameStarter/blob/master/src/main/scala/myOrg/sparklingGraph/FraudCentrality.scala to calculate the fraudulent percentage some questions are still open for me (see the TODO notes /questions at the link). 

It would be great if someone could help me to understand sparkling graph better in order to *customize* EigenvectorCentrality.

**Comment by riomus** [comment]
Just to clarify, you do not want to modify eigen vector centrality, you want to create your own new measure. You want to use Pregel operator in order to exchange data between vertices and  average that data. I think that you want to exchange (Double,Int) where Double is given vertex score and Int will be used for averaging scores of neighbours. First you nedd exchange data between vertices so each vertex send (<score>,1) and in mergeMsg function you sum those tuples: 
```
case ((score1,num1),(score2,num2))=>(score1+score2,num1+num2)
```

In the next step, you compute average just by mapping vertices values and doing division. After that you can normalize values to the [0,1] range and repeat  the whole phase as long as there are big enough changes in the network or you reach appropriate number of iterations.

**Comment by geoHeil** [comment]
You are correct. What is the implicit which needs to be in scope?
implicit num:Numeric[ED]
Could you explain that. Thanks a lot.
riomus <notifications@github.com> schrieb am Fr. 3. März 2017 um 17:16:

**Comment by riomus** [comment]
That is used in order to have a generic solution for different number types that are on edges (weights). If you know edge value type during implementation, or you do not use it (yo do not from what i see) you can remove it, but also scala compiler is handling it for you.

**Comment by geoHeil** [comment]
No I get a compilation error as it is not present.
riomus <notifications@github.com> schrieb am Fr. 3. März 2017 um 17:39:

**Comment by riomus** [comment]
As i sad you can leave it because scala will take care of that (as long as you will be using graph with numbers at edges), please share error but in my crystal ball, I see that you need to  remove 

```
extends VertexMeasure[Double]
```

**Comment by geoHeil** [comment]
That's correct. Just thought it might be a good idea to stay with the
sparkling graph protocol.
The vertices are of type id (I think float), fraud level and the resulting
metric should be double.

Edges will be labeled with the type of interaction, however, it should be
possible to ignore this type hen computing the metric.

So if I understood correctly it is not possible with this types of edges to
fulfill the contract and I should remove the interface.

Secondly, I wonder how circles in the graph are to be handled.
riomus <notifications@github.com> schrieb am Fr. 3. März 2017 um 17:45:

**Comment by riomus** [comment]
Please remember that you are not using anything that is in SparklingGrapgh right now, if you want to have vertex measure that implements SparklingGraph API in order to use it in other places in SparklingGrapgh, just leave numeric and that extend, in place. In current implementations some measures use edges values, that's why numeric is required. In your case, it is not required and it is a  specific type of a measure . But as I wrote, you can leave extend and implicit numeric, and then : pass graph with numeric edges values or provide your own numeric implementation for edge type (but you do not use it so there is no point)

**Comment by riomus** [comment]
@geoHeil  please close that issue if everything is clear.

**Comment by geoHeil** [comment]
Not 100% but we can close it for now.
Roman Bartusiak <notifications@github.com> schrieb am Di. 7. März 2017 um
22:24:

**Comment by riomus** [comment]
Feel free to ask any questions.

**Comment by geoHeil** [comment]
For https://github.com/geoHeil/graphFrameStarter/blob/master/src/main/scala/myOrg/sparklingGraph/FraudCentrality.scala#L38-L65 I am still confused whether to send to src or to dst. And regarding the type of what is exchanged: graphX always seems to associate a vertex ID with the message so a simple double should be enough. Also for the merge if I want to get the average where is the state kept to actually divide by number of elements?

**Comment by riomus** [comment]
Sending to DST or to SRC depends on what you want to achieve (if your relation that is represented by edge is undirected, you must send data to both src and dst). If you want to known who was the sender of message you must send that information by yourself, GraphX is only giving you recipient id

**Comment by geoHeil** [comment]
Sorry if it is still unclear for me. https://github.com/geoHeil/graphFrameStarter/blob/master/src/main/scala/myOrg/sparklingGraph/FraudCentrality.scala#L46-L56 is removing the implicits. But assuming every vertex initially has and ID and a fraud score how can I access that score? Assuming a directed graph is it correct that I would send the message to source?

**Comment by riomus** [comment]
for directed it means that information flows from src to destination, it depends now what your relation means, if connection mean that src contact dst and because of that src fraud score should be updated then yes, send data from dst to src. I do not know what you mean by accessing score, it has nothing to do with implicit.

**Comment by geoHeil** [comment]
I mean that the graph is initialixed by https://github.com/geoHeil/graphFrameStarter/blob/master/src/main/scala/myOrg/ExampleSQL.scala#L63-L88

```
val vertices: RDD[(VertexId, (String, Int))] =
    spark.sparkContext.parallelize(Array(
      (1L, ("Alice", 1)),
      (2L, ("Bob", 0)),
      (3L, ("Charlie", 0)),
      (4L, ("David", 0)),
      (5L, ("Esther", 0)),
      (6L, ("Fanny", 0)),
      (7L, ("Gabby", 0)),
      (8L, ("Fraudster", 1))
    ))
```
the name could be removed but ID and a 0 or 1 score should constitute the original vertex. To me it is unclear how I can access this 0, 1 value of the vertex and pass it on to the other (original message sending vertex)

Do I understand correctly that the original A---> B sending vertex (A) is called sender and (b) destination? But if I send a message to the destination (myself) why does this work?

**Comment by riomus** [comment]
GraphX is holding graph in memory as edge triplets. So a triplet of two vertices and edge between them are accessible by algorithms. You can pass information according to the direction of edge src->dst or against it dst->src, GraphX will handle it.

**Comment by geoHeil** [comment]
Yes but I so far only understood how to pass the property of the edge and
not how to send values of the vertex.
Roman Bartusiak <notifications@github.com> schrieb am Do. 9. März 2017 um
20:30:

**Comment by riomus** [comment]
In pregel you have acces to attributes of vertices (srcAttr, dstAttr)  and edge .

**Comment by riomus** [comment]
Is everything ok and clear now and you can close it now?

**Comment by geoHeil** [comment]
More or less. I will close it for now.
