### ISSUE TITLE
Calculate Eigenvector centrality with weight edges

### ISSUE THREAD

**Issue by luisfsantana** [sparkling-graph/sparkling-graph#16]
Hi everybody, 

How do I can calculate Eigenvector Centrality with weight edges?

Thank you!

**Comment by riomus** [comment]
Hi,

If you will look at ml.sparkling.graph.operators.measures.vertex.eigenvector.EigenvectorCentrality you will see in lines 37 (and 40 for undirected graphs) that we use edge weight in order to compute pre-normalization values. So in order to compute weighted eigenvector centrality, you must just have appropriate weights attached to edges and provide numeric for that weight (if it is normal Scala number that it will be provided automatically by a compiler) . Just remember that centralities for vertices are normalized, so if you have same weights for all edges then result will be same as having 1 as weights.

**Comment by riomus** [comment]
Please close the issue if everything is ok
